name: Deploy Website

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  deploy:
    name: Deploy via SCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload file to server using SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}              # Set in GitHub Secrets
          username: ${{ secrets.USERNAME }}      # Set in GitHub Secrets
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # Set in GitHub Secrets (private key content)
          port: 22                               
          source: "index.html"                   # Or folder like "dist/"
          target: "/var/www/html"                # Remote server path

          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: false
          strip_components: 0
          overwrite: true
          tar_dereference: false
          tar_exec: tar
