name: Deploy index.html to EC2 Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy index.html to EC2 server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "index.html"
          target: "${{ secrets.EC2_TARGET_DIR }}"
          scp_args: "-o StrictHostKeyChecking=no"
